import type { AirMissionOrder } from "../types.js";

const clamp = (value: number, minimum: number, maximum: number) =>
  Math.max(minimum, Math.min(maximum, value));

export interface DamageFlightPlan {
  mode: "normal" | "degraded" | "abort" | "uncontrollable";
  trimYawDeg: number;
  maximumBankDeg: number;
  maximumLoadFactor: number;
  maximumVerticalCommand: number;
  fuelLeakPerSecond: number;
  radarOperational: boolean;
  recommendedOrder: AirMissionOrder | null;
}

export function planDamageFlight(input: {
  mission: AirMissionOrder;
  maximumLoadFactor: number;
  structureHealth: number;
  leftEngineHealth: number;
  rightEngineHealth: number;
  radarHealth: number;
  flightControlHealth: number;
  weaponSystemHealth: number;
  alternativeCloseWeaponAvailable: boolean;
}): DamageFlightPlan {
  const structure = clamp(input.structureHealth / 100, 0, 1);
  const left = clamp(input.leftEngineHealth / 100, 0, 1);
  const right = clamp(input.rightEngineHealth / 100, 0, 1);
  const controls = clamp(input.flightControlHealth / 100, 0, 1);
  const engineAverage = (left + right) * 0.5;
  // Positive yaw rotates the simulation's forward (-Z) axis toward port
  // (-X). Trim must oppose the yaw generated by the healthier engine.
  const engineAsymmetry = left - right;
  const radarOperational = input.radarHealth > 12;
  const uncontrollable = structure <= 0.2 || controls <= 0.08 ||
    (left <= 0.05 && right <= 0.05);
  const abort = !uncontrollable && (structure <= 0.55 || controls <= 0.35 ||
    left <= 0.25 || right <= 0.25 || input.weaponSystemHealth <= 10 ||
    (!radarOperational &&
      ["cap", "intercept", "escort"].includes(input.mission) &&
      !input.alternativeCloseWeaponAvailable));
  const degraded = !uncontrollable && !abort &&
    (structure < 0.85 || controls < 0.8 || left < 0.8 || right < 0.8 ||
      input.radarHealth < 65);
  const fuelLeakPerSecond = Math.max(0, (0.7 - structure) * 0.34) +
    Math.max(0, 0.35 - Math.min(left, right)) * 0.22;
  return {
    mode: uncontrollable ? "uncontrollable" : abort ? "abort" :
      degraded ? "degraded" : "normal",
    trimYawDeg: clamp(engineAsymmetry * 5.5, -4.5, 4.5),
    maximumBankDeg: clamp(28 + controls * 56, 28, 84),
    maximumLoadFactor: clamp(
      1 + (input.maximumLoadFactor - 1) * controls *
        (0.58 + structure * 0.42),
      1.5,
      input.maximumLoadFactor,
    ),
    maximumVerticalCommand: clamp(0.025 + engineAverage * 0.3, 0.025, 0.325),
    fuelLeakPerSecond,
    radarOperational,
    recommendedOrder: abort ? "return" : null,
  };
}
