import { createE2cModel, createTu126Model } from "./models.js";
import type { AirPlatformDefinition, AirWeaponId } from "../types.js";

const emptyLoadout = ():Record<AirWeaponId,number> => ({"AIM-54A":0,"AIM-54X-CEC":0,"AIM-7F":0,"AIM-9L":0,"R-27R":0,"R-73":0,"KSR-5":0,"AGM-84A":0});
const turbopropThrust={militarySpeedFactor:1.18,militaryAccelerationFactor:1,militaryFuelMultiplier:1.42,militaryInfraredMultiplier:1.12,afterburnerAvailable:false,afterburnerSpeedFactor:1.18,afterburnerAccelerationFactor:1,afterburnerFuelMultiplier:1.42,afterburnerInfraredMultiplier:1.12,afterburnerSeconds:0};
const e2cAerodynamics={referenceMassKg:23000,wingAreaM2:65,zeroLiftDragCoefficient:.034,inducedDragFactor:.072,liftCurveSlopePerDeg:.082,criticalAngleOfAttackDeg:15,controlResponseSeconds:1.25,engineSpoolUpSeconds:6.5,engineSpoolDownSeconds:5.2};
const tu126Aerodynamics={referenceMassKg:150000,wingAreaM2:311,zeroLiftDragCoefficient:.036,inducedDragFactor:.075,liftCurveSlopePerDeg:.072,criticalAngleOfAttackDeg:12,controlResponseSeconds:1.8,engineSpoolUpSeconds:8.2,engineSpoolDownSeconds:6.8};

export const AEW_PLATFORM_DEFINITIONS:readonly AirPlatformDefinition[]=[
  {id:"E-2C",name:"E-2C Hawkeye",nation:"United States",role:"Carrier airborne early warning",mission:"aew",radarCrossSection:14.5,infraredSignature:1.05,flight:{cruiseSpeed:3.25,maxSpeed:4.5,stallSpeed:1.55,acceleration:.38,drag:.024,maxLoadFactor:3,maxRollRateDeg:42,maxPitchRateDeg:10,fuelSeconds:1800,aerodynamics:e2cAerodynamics,thrust:turbopropThrust},sensor:{name:"AN/APS-125",range:3200,updateInterval:4.8,fieldOfViewDeg:360,precision:.78,coverage:"rotating-360"},datalink:{link11:true,link11NetControlCapable:true,terminalName:"AN/ARC-158 TADIL-A",terminalReliability:.9,timeSyncQuality:.74},aewCommand:{mode:"link4a",controllerCapacity:2,commandDelay:1.2,commandLife:10,reliability:.94,fighterPlatformIds:["F-14A"]},ecm:{strength:.32,burnThroughRange:24},countermeasures:{chaff:18,flares:12,program:{chaffBurst:3,flareBurst:2,interval:.2,cooldown:7,triggerTti:24}},loadout:emptyLoadout(),fireControlChannels:{datalink:0,illumination:0},hardpoints:[],buildModel:createE2cModel,shipDefenseTemplate:"Kh-22"},
  {id:"TU-126",name:"Tu-126 Moss",nation:"Soviet Union",role:"Airborne early warning",mission:"aew",radarCrossSection:145,infraredSignature:1.8,flight:{cruiseSpeed:3.9,maxSpeed:5.85,stallSpeed:1.75,acceleration:.32,drag:.026,maxLoadFactor:2.5,maxRollRateDeg:24,maxPitchRateDeg:7,fuelSeconds:2600,aerodynamics:tu126Aerodynamics,thrust:turbopropThrust},sensor:{name:"Liana",range:2800,updateInterval:7.2,fieldOfViewDeg:360,precision:.62,coverage:"rotating-360"},aewCommand:{mode:"voice-gci",controllerCapacity:1,commandDelay:4.5,commandLife:16,reliability:.78,fighterPlatformIds:["MIG-29A"]},ecm:{strength:.58,burnThroughRange:42},countermeasures:{chaff:30,flares:8,program:{chaffBurst:5,flareBurst:2,interval:.22,cooldown:8,triggerTti:28}},loadout:emptyLoadout(),fireControlChannels:{datalink:0,illumination:0},hardpoints:[],buildModel:createTu126Model,shipDefenseTemplate:"Kh-22"},
];
